// Poincare-disk hyperbolic tiling generator, Schlafli symbol {p,q}.
//
// The fundamental region is a regular hyperbolic p-gon centred at the disk
// origin, sized so exactly q copies meet at every vertex. Its circumradius
// (in the Poincare disk model) comes from the standard right-triangle
// relation for a {p,q} tiling: split the polygon into 2p right triangles
// with vertices at the centre O, an edge midpoint M and a polygon vertex V
// (angle pi/2 at M, pi/p at O, pi/q at V). The hyperbolic-trig identity for
// that triangle's hypotenuse gives
//     cosh(R_hyp) = cot(pi/p) * cot(pi/q)
// and the Euclidean disk radius of a point at hyperbolic distance R_hyp from
// the origin is r = tanh(R_hyp / 2). The tiling exists only when this cosh
// argument exceeds 1, i.e. (p-2)(q-2) > 4; otherwise {p,q} tiles the sphere
// or the Euclidean plane instead of the hyperbolic plane, so invalid (p,q)
// fall back to the default {7,3} (noted below).
//
// The rest of the tiling is generated by hyperbolic reflection: reflecting
// a polygon across one of its own edges (a hyperbolic geodesic) gives the
// unique adjacent tile sharing that edge. A geodesic between two points a,b
// inside the unit disk is the arc of the unique circle through a and b that
// is orthogonal to the unit circle (or, in the degenerate case where a, b
// and the origin are collinear, the straight diameter through them).
// Reflecting across that geodesic is exactly inversion in that orthogonal
// circle. Repeatedly reflecting the fundamental polygon across its edges,
// breadth-first, up to `depth` levels, generates the local tiling; polygons
// are de-duplicated by their rounded centroid since the same tile is often
// reached by more than one reflection path.
//
// This is a single hyperbolic motif centred in the tile box (mapped from
// the unit disk to a circle of radius min(width,height)/2 - 1), NOT a
// periodic Euclidean lattice, so it is NOT seamless across tile edges.
// Dense {p,q}/depth combinations are truncated by a polygon count and a
// rendered-point budget rather than by fully enumerating the (exponentially
// growing) combinatorial ball, so very deep or highly curved requests
// render an incomplete but still representative patch of the tiling.

import type { Generator, GeneratorContext, ParamValue, Pt, TileCurve } from './types'
import { getNum } from './types'

const POLY_CAP = 3000
const POINT_BUDGET = 7800

function cot(x: number): number {
  return 1 / Math.tan(x)
}

/** Euclidean (Poincare disk) circumradius of the regular {p,q} fundamental polygon. */
function diskRadius(p: number, q: number): number {
  const arg = cot(Math.PI / p) * cot(Math.PI / q)
  const Rhyp = Math.acosh(Math.max(1 + 1e-9, arg))
  return Math.tanh(Rhyp / 2)
}

function fundamentalPolygon(p: number, r: number): Pt[] {
  const pts: Pt[] = []
  for (let i = 0; i < p; i++) {
    const ang = -Math.PI / 2 + (2 * Math.PI * i) / p
    pts.push([r * Math.cos(ang), r * Math.sin(ang)])
  }
  return pts
}

/** Circle orthogonal to the unit circle passing through a and b (both
 * strictly inside the unit disk). Returns null if a, b and the origin are
 * (numerically) collinear, in which case the geodesic is the diameter line
 * through them instead. */
function orthogonalCircle(a: Pt, b: Pt): { cx: number; cy: number; r: number } | null {
  const A11 = 2 * a[0], A12 = 2 * a[1], A21 = 2 * b[0], A22 = 2 * b[1]
  const det = A11 * A22 - A12 * A21
  if (Math.abs(det) < 1e-9) return null
  const B1 = a[0] * a[0] + a[1] * a[1] + 1
  const B2 = b[0] * b[0] + b[1] * b[1] + 1
  const cx = (B1 * A22 - B2 * A12) / det
  const cy = (A11 * B2 - A21 * B1) / det
  const r2 = cx * cx + cy * cy - 1
  if (r2 <= 1e-9) return null
  return { cx, cy, r: Math.sqrt(r2) }
}

function reflectAcrossLine(p: Pt, a: Pt, b: Pt): Pt {
  const dx = b[0] - a[0], dy = b[1] - a[1]
  const len2 = dx * dx + dy * dy
  if (len2 < 1e-12) return p
  const t = ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / len2
  const projx = a[0] + t * dx, projy = a[1] + t * dy
  return [2 * projx - p[0], 2 * projy - p[1]]
}

/** Hyperbolic reflection of every vertex of `poly` across the geodesic
 * through a,b (inversion in the orthogonal circle, or Euclidean line
 * reflection in the degenerate diameter case). */
function reflectPolygon(poly: Pt[], a: Pt, b: Pt): Pt[] {
  const circ = orthogonalCircle(a, b)
  if (!circ) return poly.map((p) => reflectAcrossLine(p, a, b))
  const { cx, cy, r } = circ
  const r2 = r * r
  return poly.map((p) => {
    const dx = p[0] - cx, dy = p[1] - cy
    const d2 = dx * dx + dy * dy
    if (d2 < 1e-12) return p
    const k = r2 / d2
    return [cx + dx * k, cy + dy * k] as Pt
  })
}

/** Sample the geodesic arc from a to b (unit-disk coordinates) with
 * segments no longer than ~0.4mm / ~6 degrees once scaled by `Rbox`. */
function geodesicArcPoints(a: Pt, b: Pt, Rbox: number): Pt[] {
  const circ = orthogonalCircle(a, b)
  if (!circ) return [a, b]
  const { cx, cy, r } = circ
  const a0 = Math.atan2(a[1] - cy, a[0] - cx)
  const a1raw = Math.atan2(b[1] - cy, b[0] - cx)
  let diff = a1raw - a0
  while (diff <= -Math.PI) diff += 2 * Math.PI
  while (diff > Math.PI) diff -= 2 * Math.PI
  const sweepShort = diff
  const sweepLong = diff - Math.sign(diff || 1) * 2 * Math.PI
  const normAt = (ang: number) => Math.hypot(cx + r * Math.cos(ang), cy + r * Math.sin(ang))
  const midShort = a0 + sweepShort / 2
  const midLong = a0 + sweepLong / 2
  // The correct arc is the one that stays inside the unit disk, i.e. whose
  // midpoint sits closer to the origin.
  const sweep = normAt(midShort) <= normAt(midLong) ? sweepShort : sweepLong
  const segsByAngle = Math.abs(sweep) / (6 * Math.PI / 180)
  const segsByLength = (Math.abs(sweep) * r * Rbox) / 0.4
  const segs = Math.max(1, Math.ceil(Math.max(segsByAngle, segsByLength)))
  const pts: Pt[] = []
  for (let i = 0; i <= segs; i++) {
    const ang = a0 + (sweep * i) / segs
    pts.push([cx + r * Math.cos(ang), cy + r * Math.sin(ang)])
  }
  return pts
}

function centroid(poly: Pt[]): Pt {
  let cx = 0, cy = 0
  for (const p of poly) { cx += p[0]; cy += p[1] }
  return [cx / poly.length, cy / poly.length]
}

function centroidKey(poly: Pt[]): string {
  const [cx, cy] = centroid(poly)
  return `${cx.toFixed(4)},${cy.toFixed(4)}`
}

/** Rough diameter of a polygon (unit-disk units), used to decide whether a
 * tile has already shrunk below minFeature and should stop spawning further
 * reflections. */
function approxDiameter(poly: Pt[]): number {
  const [cx, cy] = centroid(poly)
  let maxd = 0
  for (const p of poly) maxd = Math.max(maxd, Math.hypot(p[0] - cx, p[1] - cy))
  return maxd * 2
}

function ptKey(p: Pt): string {
  return `${p[0].toFixed(4)},${p[1].toFixed(4)}`
}

function edgeKey(a: Pt, b: Pt): string {
  const ka = ptKey(a), kb = ptKey(b)
  return ka < kb ? `${ka}|${kb}` : `${kb}|${ka}`
}

function pointLineDist(p: Pt, a: Pt, b: Pt): number {
  const dx = b[0] - a[0], dy = b[1] - a[1]
  const len = Math.hypot(dx, dy)
  if (len < 1e-9) return Math.hypot(p[0] - a[0], p[1] - a[1])
  return Math.abs((p[0] - a[0]) * dy - (p[1] - a[1]) * dx) / len
}

export const hyperbolicGenerator: Generator = {
  id: 'hyperbolic',
  name: 'Hyperbolic tiling',
  description: 'Poincare-disk {p,q} tiling in a centred disk. Repeating it produces visible medallions, not an all-over surface pattern.',
  seamless: () => true,
  params: [
    { key: 'width', label: 'Width', type: 'number', default: 40, min: 5, max: 300, step: 1 },
    { key: 'height', label: 'Height', type: 'number', default: 40, min: 5, max: 300, step: 1 },
    { key: 'p', label: 'Polygon sides (p)', type: 'int', default: 7, min: 3, max: 12, step: 1, hint: 'sides of the tile polygon' },
    { key: 'q', label: 'Meeting at vertex (q)', type: 'int', default: 3, min: 3, max: 12, step: 1, hint: 'tiles meeting at each vertex' },
    { key: 'depth', label: 'Reflection depth', type: 'int', default: 4, min: 1, max: 6, step: 1 },
    {
      key: 'style', label: 'Style', type: 'select', default: 'edges',
      options: [
        { value: 'edges', label: 'Edges (geodesic arcs)' },
        { value: 'cells', label: 'Cells (inset polygons)' },
      ],
    },
    { key: 'ribWidth', label: 'Rib width', type: 'number', default: 1.2, min: 0.3, max: 4, step: 0.1, hint: 'used by the edges style' },
    { key: 'gap', label: 'Cell gap', type: 'number', default: 0.8, min: 0.1, max: 4, step: 0.1, hint: 'used by the cells style' },
    { key: 'minFeature', label: 'Min feature', type: 'number', default: 1, min: 0.2, max: 5, step: 0.1 },
    { key: 'seed', label: 'Seed', type: 'int', default: 1, min: 0, max: 999999, step: 1, hint: 'unused: the tiling is fully deterministic' },
  ],
  generate(params: Record<string, ParamValue>, _ctx: GeneratorContext) {
    const width = getNum(params, 'width', 40)
    const height = getNum(params, 'height', 40)
    let p = Math.round(getNum(params, 'p', 7))
    let q = Math.round(getNum(params, 'q', 3))
    p = Math.min(12, Math.max(3, p))
    q = Math.min(12, Math.max(3, q))
    if ((p - 2) * (q - 2) <= 4) {
      // {p,q} would tile the sphere or Euclidean plane, not hyperbolic
      // space (Descartes/Gauss-Bonnet needs (p-2)(q-2) > 4); fall back to
      // the classic {7,3} heptagonal tiling.
      p = 7
      q = 3
    }
    const depth = Math.max(1, Math.round(getNum(params, 'depth', 4)))
    const style = String(params.style ?? 'edges')
    const ribWidth = getNum(params, 'ribWidth', 1.2)
    const gap = getNum(params, 'gap', 0.8)
    const minFeature = Math.max(0.05, getNum(params, 'minFeature', 1))

    const cx = width / 2, cy = height / 2
    const Rbox = Math.max(0.5, Math.min(width, height) / 2 - 1)
    const toBox = (pt: Pt): Pt => [cx + pt[0] * Rbox, cy + pt[1] * Rbox]

    const r0 = diskRadius(p, q)
    const root = fundamentalPolygon(p, r0)
    const seen = new Map<string, Pt[]>()
    seen.set(centroidKey(root), root)
    let frontier: Pt[][] = [root]

    for (let d = 0; d < depth && seen.size < POLY_CAP; d++) {
      const next: Pt[][] = []
      for (const poly of frontier) {
        const sizeMm = approxDiameter(poly) * Rbox
        if (sizeMm < minFeature) continue // too small to usefully subdivide further
        for (let i = 0; i < poly.length; i++) {
          const a = poly[i], b = poly[(i + 1) % poly.length]
          const refl = reflectPolygon(poly, a, b)
          const key = centroidKey(refl)
          if (seen.has(key)) continue
          seen.set(key, refl)
          next.push(refl)
          if (seen.size >= POLY_CAP) break
        }
        if (seen.size >= POLY_CAP) break
      }
      frontier = next
    }

    const polygons: Pt[][] = []
    const curves: TileCurve[] = []
    let used = 0

    if (style === 'cells') {
      for (const poly of seen.values()) {
        if (used >= POINT_BUDGET) break
        const boundary: Pt[] = []
        for (let i = 0; i < poly.length; i++) {
          const a = poly[i], b = poly[(i + 1) % poly.length]
          const seg = geodesicArcPoints(a, b, Rbox)
          const start = boundary.length === 0 ? 0 : 1
          for (let k = start; k < seg.length; k++) boundary.push(seg[k])
        }
        if (boundary.length > 1) {
          const f = boundary[0], l = boundary[boundary.length - 1]
          if (Math.hypot(f[0] - l[0], f[1] - l[1]) < 1e-9) boundary.pop()
        }
        if (boundary.length < 3) continue
        const boxPoly = boundary.map(toBox)
        const [ccx, ccy] = centroid(boxPoly)
        let apothem = Infinity
        const n = boxPoly.length
        for (let i = 0; i < n; i++) {
          apothem = Math.min(apothem, pointLineDist([ccx, ccy], boxPoly[i], boxPoly[(i + 1) % n]))
        }
        const insetR = apothem - gap
        if (insetR * 2 < minFeature) continue // shrinks below the minimum feature size near the rim
        const scale = insetR / apothem
        const inset = boxPoly.map((pt) => [ccx + (pt[0] - ccx) * scale, ccy + (pt[1] - ccy) * scale] as Pt)
        polygons.push(inset)
        used += inset.length
      }
    } else {
      const edgeSeen = new Set<string>()
      outer: for (const poly of seen.values()) {
        for (let i = 0; i < poly.length; i++) {
          if (used >= POINT_BUDGET) break outer
          const a = poly[i], b = poly[(i + 1) % poly.length]
          const key = edgeKey(a, b)
          if (edgeSeen.has(key)) continue
          edgeSeen.add(key)
          const seg = geodesicArcPoints(a, b, Rbox).map(toBox)
          curves.push({ points: seg, closed: false })
          used += seg.length
        }
      }
    }

    return { width, height, polygons, curves, ribWidth }
  },
}
